### ISSUE TITLE
Step1: falta testar ""

### ISSUE THREAD

**Issue by thiagohersan** [NicholasNeto/string_Calculator_Kata#1]
na descrição do problema ta escrito pra testar "" (string vazio).
Esse [teste](https://github.com/NicholasNeto/string_Calculator_Kata/blob/bcb6f80a1663794c0c1bdd0e0ea7225f9abbd6c9/test/step1.js#L9) é para " " (o caracter de espaço).

Pode ser bom testar os dois nesse primeiro step...

**Comment by NicholasNeto** [comment]
Atendendo os criterios do teste ferente a mandar uma string vazia , add('')

melhoria no commit :   46effef189c26df770c15cd933d9d9b2532d4f48
