### ISSUE TITLE
Bug: delimitador

### ISSUE THREAD

**Issue by thiagohersan** [NicholasNeto/string_Calculator_Kata#10]
Gostei que você implementou a lógica para strings bem complexos, tipo:
```"//*\n1*2*3,4,5,6\n7\n8\n9"```

Mas, tem um bug, e o teste está falhando nas duas últimas somas:
<img width="466" alt="screen shot 2018-02-23 at 13 37 17" src="https://user-images.githubusercontent.com/850815/36605166-b450f97e-189e-11e8-8066-a067a6c6d512.png">

<img width="528" alt="screen shot 2018-02-23 at 13 38 12" src="https://user-images.githubusercontent.com/850815/36605213-d63fc330-189e-11e8-8dee-513c53146d19.png">

(e, você deixou um ```.only``` [no arquivo de testes](https://github.com/NicholasNeto/string_Calculator_Kata/blob/master/test/step4.js#L37) : )

**Comment by NicholasNeto** [comment]
Isso acontecia pq eu não tava prevendo um numero depois dos delimitadores , e não estava prevendo possíveis quebra de linha .

**Comment by thiagohersan** [comment]
Sim. Eu acho que você consegue modificar o código para lidar com tudo isso.

Tem um negócio complicado com regexp que vai ser bom aprender (eu ainda não sei fazer também....)
