### ISSUE TITLE
step6: listaNumerosMaiores1000()

### ISSUE THREAD

**Issue by thiagohersan** [NicholasNeto/string_Calculator_Kata#12]
O nome dessa função deveria ser:
``` listaNumerosMenores1000()```

**Comment by NicholasNeto** [comment]
verdade , pq o filtro é de 0 ate 1000 o resto eu ignoro , antes eu estava pensando em fazer uma lista com os numeros maiores e ignorar-los  depois , mas não faz sentindo ... 

então criei uma lista de coisas que eu realmente queria usar , mas esqueci de renomear a function

**Comment by thiagohersan** [comment]
Agora o código não está rodando. Ainda tem alguns lugares que estão com listaNumerosMaiores1000 ou numerosMaior1000...

**Comment by NicholasNeto** [comment]
afaf1a5609b938a6f897e6ece2c22053d95dc0b2

feito
