### ISSUE TITLE
Step1: Quanto menos código, melhor

### ISSUE THREAD

**Issue by thiagohersan** [NicholasNeto/string_Calculator_Kata#2]
[Esse if](https://github.com/NicholasNeto/string_Calculator_Kata/blob/master/step1.js#L8-L11) não está fazendo o que você acha que ele está fazendo. Ele é ```true``` para strings de um só caracter (ou um só dígito), e não listas de um só elemento.

[Essa parte aqui](https://github.com/NicholasNeto/string_Calculator_Kata/blob/bcb6f80a1663794c0c1bdd0e0ea7225f9abbd6c9/step1.js#L13-L19) está bem massa. Ótimo uso de ```reduce()```.

Será que esse ```reduce()``` não resolve o caso de um só número também? Independente do número de dígitos?

Quem tá fazendo as contas no caso de ```add("123")``` ? 
O ```if(dados.length === 1)``` ou o ```if(dados.length > 1)``` ?

**Comment by NicholasNeto** [comment]
EU  entendi e aprendi agora ....

Eu aprendi um pouco mais sobre o comportamento do reduce()

EU achava que se eu mandava pra ele uma string ' 1234'   ele iria desmembrar numero por numero  e tentar fazer a soma de cada numero .... primeiro 1 , depois  2, depois 3  ... etc 

Alguns trabalham com a string como se fosse uma lista , por isso minha preocupação de utilizar o reduce()

mas voce tem razão ...

ele serve e muito bem , pra um numero só ou para mais numeros ...


conhecimento adquirido e  refatorado : 0af0e7ddbdcd0eb1800986c8c4d468594455fc56

obrigado

**Comment by thiagohersan** [comment]
não sei o que acontece se você manda um string pro ```reduce()```, pode ser que ele quebre letra por letra ou dígito por dígito.

Mas você sempre esteve mandando uma lista, criada com:
```var listaNumeros = dados.split(',');```

Mesmo tendo só um elemento, ainda é uma lista e o ```reduce()``` só vai executar nesse único elemento.
