### ISSUE TITLE
Step1: Mais testes!

### ISSUE THREAD

**Issue by thiagohersan** [NicholasNeto/string_Calculator_Kata#3]
Não precisa adicionar mais tipos de testes, mas no caso de algo matemático que tem algumas possibilidades de números de input, vale a pena jogar alguns testes diferentes pra sua função.

Por exemplo, testar:
- números com mais de 1 dígito: ```add("123");``` ,  ```add("123,456");```
- números negativos: ```add("-789");``` ,  ```add("123,-321");``` , ```add("-555,-666");```
- zero: ```add("0");``` ,  ```add("0, 1234");``` , ```add("0,0");```

**Comment by NicholasNeto** [comment]
add("123"); 

testar nesta condição , acho que era o teste que me faltava pra notar o grande problema que eu tinha com o if (dados.length === 1)

Obrigado ...

não vou aplicar números negativos agora , pq  acho que tem um step mais pra frente que vala sobre isso ...

 se eu já começar a implementar números negativos  , vou quebrar o exercício de fazer minimo de esforço possível e depois refatorar ...


embora eu concorde que seria bom , fazer minimo de esforço possível , inteligentes  tipo este casso que vc me passou de mandar testar  com uma string de 3 dígitos .

**Comment by thiagohersan** [comment]
Ok. Acho que a especificação do kata está meio ambígua sobre os números negativos. Pode deixar sem testar.
