### ISSUE TITLE
Step2: não precisa separar os testes por step

### ISSUE THREAD

**Issue by thiagohersan** [NicholasNeto/string_Calculator_Kata#4]
Apesar de eu ter falado pra fazer um arquivo por step, imagina que para os testes cada step é como se fosse o step final. Ou seja, testa tudo junto. Não precisa separar os testes por step [assim](https://github.com/NicholasNeto/string_Calculator_Kata/blob/bcb6f80a1663794c0c1bdd0e0ea7225f9abbd6c9/test/step2.js#L20)

Acho melhor separar por caso, ou seja, deixar só os ```it()```.

**Comment by NicholasNeto** [comment]
OK, entendido 

Já melhorado ..

**Comment by thiagohersan** [comment]
Olhando aqui:
https://github.com/NicholasNeto/string_Calculator_Kata/blob/master/test/step2.js

Acho que não precisa especificar os steps nos testes, porque todos os testes tem que passar, independente do step. O nome do arquivo já identifica em qual step você está.

Por exemplo, [esse teste](https://github.com/NicholasNeto/string_Calculator_Kata/blob/master/test/step2.js#L31-L33) é o mesmo que [esse](https://github.com/NicholasNeto/string_Calculator_Kata/blob/master/test/step2.js#L19-L21). Você pode juntar os dois e chamar de "permitir que add receba dois números". E pode testar as duas somas dentro do ```it()```:

```
it('Quando enviado dois numeros retorne a soma dos dois', () => {
  expect(add('1,2')).to.equal(3);
  expect(add('33,45')).to.equal(78);
});
```

--- 
[Esse teste](https://github.com/NicholasNeto/string_Calculator_Kata/blob/master/test/step2.js#L27-L29) é redundante, já tem no step 1: https://github.com/NicholasNeto/string_Calculator_Kata/blob/master/test/step2.js#L11-L13

Aliás: [esse](https://github.com/NicholasNeto/string_Calculator_Kata/blob/master/test/step2.js#L11-L13) e [esse](https://github.com/NicholasNeto/string_Calculator_Kata/blob/master/test/step2.js#L15-L17) podem etsar dentro do mesmo ```it()```.

---
Testar a especificação que fala "receber quantidade desconhecida de números" com um teste só é meio fraco. Porque você só está testando uma soma de 6 números. 

Você podia testar umas somas com 3, 4, 5, 10 e 6 números dentro desse ```it()```:
https://github.com/NicholasNeto/string_Calculator_Kata/blob/master/test/step2.js#L35-L37

**Comment by NicholasNeto** [comment]
OK , 

Só não entendi esta ultima parte !
---
Testar a especificação que fala "receber quantidade desconhecida de números" com um teste só é meio fraco. Porque você só está testando uma soma de 6 números.

Você podia testar umas somas com 3, 4, 5, 10 e 6 números dentro desse it():
https://github.com/NicholasNeto/string_Calculator_Kata/blob/master/test/step2.js#L35-L37
---


não entendi 


talvez seja isso : 7614c480749ae975a448b222369a90c6a0b870b7  :+1:

**Comment by NicholasNeto** [comment]
melhorado no commit : f9b60852c41645544048acb33cf0408cc1424e70

**Comment by thiagohersan** [comment]
Desculpa. Não fui claro.

Você está testando a condição de que a função pode "receber quantidade desconhecida de números". Mas no teste, você só tem um ```expect()```, que é uma soma de 6 números (1+2+3+4+5+6). Então, na verdade você só está testando que a função consegue somar 6 números e não "uma quantidade desconhecida de números".

É impossível testar todas as possibilidades, né, mas acho que poderia ter mais ```expect()``` dentro do ```it()```.

Por exemplo:
```
it('Permitir que add receba quantidade desconhecida de números (passando mais de dois numeros)', () => {
  expect(add('1,2,3,4,5,6')).to.equal(21);
  expect(add('1,2,123,4,235,6,2345')).to.equal(2716);
  expect(add('10,20,30')).to.equal(60);
  expect(add('1,20,30,50')).to.equal(101);
  expect(add('1,2,3,5,8,13,21,34,55,89')).to.equal(231);
});
```

**Comment by thiagohersan** [comment]
O commit f9b6085 tá massa. Era isso mesmo ! Show.

**Comment by NicholasNeto** [comment]
melhorado
