### ISSUE TITLE
Tomar cuidado com returns implícitos

### ISSUE THREAD

**Issue by thiagohersan** [NicholasNeto/string_Calculator_Kata#5]
É bom sempre deixar explícito o return de funções.

Na função ```stringVazia()``` não está claro o que ela vai retornar no caso do ```if()``` ser falso.

```
var stringVazia = function (entrada) {
  if (entrada === '') {
    return true
  }
}
```

Se você definir essa função no node e chamar ```stringVazia('1,2,3')```, vai ver que o return é ```undefined``` e não ```false```. 

Sorte sua que [aqui](https://github.com/NicholasNeto/string_Calculator_Kata/blob/master/step3.js#L5-L7) ```if(undefined)``` tem comportamento igual a ```if(false)```.

**Comment by NicholasNeto** [comment]
algumas vezes estou arrumando mais de uma coisa no mesmo commit 

abf2f295f689e221f44360de784e40e97eef6b45

**Comment by thiagohersan** [comment]
Massa. Mas olha o #6 e vê se tem como simplificar essa função.
