### ISSUE TITLE
return true, if x === true, ...

### ISSUE THREAD

**Issue by thiagohersan** [NicholasNeto/string_Calculator_Kata#6]
Quase nunca é necessário escrever ```true``` ou ```false``` no código. Excessão é quando estiver dando valor inicial à alguma variável (```var x = true```).

Mas quando for checar se uma variável é igual a ```true```, é mais simples fazer assim:
```
if(x) {
  // bla bla bla...
}
```

Do que assim:
```
if(x === true) {
  // bla bla bla...
}
```

No caso de checar ```false```:
```
if(!x) {
  // bla bla bla...
}
```

É mais elegante que
```
if(x === false) {
  // bla bla bla...
}
```

---
Mesma coisa quando tiver um return. Ao invés de:
```
if(x) {
  return true
}
```

É mais simples e seguro colocar:
```
return x
```

Isso resolveria o problema do #5 .

**Comment by thiagohersan** [comment]
A função ```stringVazia()``` poderia ficar mais simples:
https://github.com/NicholasNeto/string_Calculator_Kata/blob/master/step3.js#L26-L32

**Comment by thiagohersan** [comment]
```
if(x === 'foo') {
  return true
} else {
  return false
}
```

é a mesma coisa que:
```
return (x === 'foo')
```

**Comment by NicholasNeto** [comment]
Demorou um pouco pra entender , mas é isso que voce quis dizer : a88d45c7d216c3d83e65f5ba7610c91616d4193b

agora eu só queria entender por que deste jeito é mais "seguro " pra mim parece a mesma coisa !

**Comment by thiagohersan** [comment]
O que está dentro do ```if()``` ficou igualzinho o que está dentro do ```else```. Se o que está dentro do ```if``` é igualzinho o que está dentro do ```else```, a função sempre retorna a mesma coisa, não precisa do ```if/else```. Pode tirar o ```if/else``` e deixar só: ```return (entrada === '')```.

É mais seguro porque não tendo ```if/else``` não tem como esquecer o ```else``` (igual você esqueceu nas primeiras versões do código).
