### ISSUE TITLE
Função criaLista() está mega complexa

### ISSUE THREAD

**Issue by thiagohersan** [NicholasNeto/string_Calculator_Kata#7]
Eu entendi que você está primeiro dividindo o string nos ```'\n'```, e depois re-dividindo os sub-strings nos ```','```  mas não entendo porque precisa do ```isNan()```.

De qualquer forma, tem muito código. E quanto mais código, maior a probabilidade de ter bugs.

Não seria mais fácil só detectar onde tem ```'\n'``` no string original e trocar por ```','```?
Depois é só seguir com o mesmo código de sempre...

Acho que isso ajudaria: [string replace](https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Reference/Global_Objects/String/replace).

Você precisa de uma forma de fazer um ```replace()``` global. Talvez precise usar regexp.

**Comment by NicholasNeto** [comment]
O código estava com um bug ,  eu inicialmente achei que os split() estavam colocando uma virgula em algum index da lista , e então eu utilizei o isNaN pra checar se era realmente números o que estava entrando , No final das contas vi que o que realmente estava entrando era uma string vazia. 

por isso usei o string vazia ali tbm .. mas acabei não tirando o isNaN , pra eu sempre estar garantindo que o que entrava na lista era realmente números, 

ashuashaus .. 

E eu achando que tava evoluindo , por alguns minutos achei que meu cdg estava BEM melhor que o antigo ...ashuashau ...

putz , voce tem razão !!!! 

Eu poderia substituir os \n  por ,  nunca tinha pensando nisso , da até raiva como voce lembra destas possibilidades e eu não ... rsrs ..  

Mas me tira uma duvida , eu sei que aqui estamos treinando e tals , mas no mundo real com regras de negocio e regras rígidas para uma excelência de código, todo este bla bla bla ... 

fazer isso é uma boa pratica , ficar manipulando os dados assim , alterando eles e tals ? 


👍  vou  relembrar como se usa este replace() eu já o conheço mas não este regexp  ,  e não entendi muito bem um replace() global , sei o que é uma variável global (algo que vai estar acessivel para toda a aplicação)  mas uma function  que já nativa de javascript sendo global nao entendi muito bem.

**Comment by NicholasNeto** [comment]
Serio , agora eu acho mesmo que esta legal, olha : 2c9e2f507401345131c1d673f6cc7f417942a36e

as expressões regulares são complicadas  é um nivel HARD ..


Eu gostei como ela ficou agora =) 👍 

rsrsrs

**Comment by thiagohersan** [comment]
Oi. Acho que você já descobriu o lance do "global"... quando for fazer substituições em string, global significa buscar todos os lugares onde o padrão aparece. É o 'g' no final da regexp.

É normal modificar dados do usuário que chegam numa aplicação. Ainda mais se forem string. As vezes é preciso detectar e remover strings "maliciosos" (vírus, etc) que as pessoas colocam em formulários de site.

Só umas coisinhas pra deixar top:
[Precisa desse if](https://github.com/NicholasNeto/string_Calculator_Kata/blob/master/step3.js#L7-L11)?
Precisa separar o replace em uma função?
O que acontece se rodar ```dados.replace(/\n/g, ',')``` num string sem ```'\n'```? Quebra?

--- 
Não entendi o lance do ```replace(/,,/g, ',0,')```. Do jeito que está especificado o problema não deveria ter string com duas vírgulas seguidas, nem com ```'\n'``` seguido de vírgulas.

Na especificação fala:
*the following input is NOT ok:* ```"1,\n"```
Ou seja ```,\n``` não vai aparecer no input. Da onde mais vem duas vírgulas seguidas??

Ou, outro jeito de perguntar isso das vírgulas...

Qual teste falha se tirar esse replace: ```replace(/,,/g, ',0,')``` ?

**Comment by thiagohersan** [comment]
Ou, outro jeito de perguntar isso das vírgulas...

Qual teste falha se tirar esse replace: ```replace(/,,/g, ',0,')``` ?

**Comment by NicholasNeto** [comment]
1 ) Eu tava usando este segundo replace , que eu fiz uma entrada no teste errada mesmo tinha uma que estava asism : 

"22,33,44\n33,\n43"

Esta virgula depois do 33 acabava zoando tudo. Mas agora vou mudar. 

Commit :   1ed2a3fc179e6e6638c49e8a9ebcfd589588383a


2) pensei em deixar este replace numa function separada pq imaginei que estaria melhor organizado, eu tbm tava pensado em sempre ter um cdg reaproveitavel ,  mas hoje não tenho mesmo a necessidade de reaproveitar ele em nem um outro lugar . 

fico imaginando, como os programadores tomam a decisão de já escrever um cdg reaproveitavel dentro de uma function ,  só quando eles estão vendo que esta repetindo , ou é melhor já ir separando as coisas desde o começo pra reaproveitar e  até mesmo para ajudar manutenções futuras .. 

Eu acha que era melhor já sair colocando e guardando tudo que puder e coisas independentes ou especificas em functions 


Commit :   9c0d83ebaa6c72dbd443b0966f29ce895b1cb63b

3) Eu entendi pq o g tinha que estar ali e pra que ele serve 

4) Brigado, então de boas modificar os dados , eu ainda acho perigoso , mas realmente , se não modificarmos  como iríamos trabalhar neh ?! ... rs 
Legal !!

**Comment by thiagohersan** [comment]
1. Massa.

2. Geralmente, sim, é melhor colocar pedaços de código dentro de funções para deixar tudo mais organizado e re-utilizável, mas nesse caso a função ficou tão simples que ```criaLista(dados)``` só chamava ```replace(/\n/g, ',')```. Uma função que só encapsula outra função pode complicar mais o código, ainda mais quando ```replace()``` é uma função padrão do javaScript.

3. Massa.

4. Se precisar, você pode copiar os dados originais e manter uma cópia.
