### ISSUE TITLE
README.md

### ISSUE THREAD

**Issue by thiagohersan** [NicholasNeto/string_Calculator_Kata#8]
Pode colocar esse README no repositório?
https://github.com/xpeppers/string-calculator-kata/blob/master/README.md

((é esse que você está seguindo, né?))

**Comment by NicholasNeto** [comment]
Existe uma forma de copiar o mesmo README  ? com as mesmas formatações 

Eu só copiei e colei , queria fazer um tipo de fork só no readme

**Comment by thiagohersan** [comment]
Ou copia e cola o arquivo raw:
https://raw.githubusercontent.com/xpeppers/string-calculator-kata/master/README.md

Ou baixa o zip do repositório e sobe o README.md pro seu repositório:
https://github.com/xpeppers/string-calculator-kata/archive/master.zip

**Comment by NicholasNeto** [comment]
README ,  esta salvo 

7e89a4a228991c5dec9ca18ed9e5b77250e6b1aa
